/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.jogodavelha;

import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.border.TitledBorder;

/**
 *
 * @author falvojr
 */
public class Tabuleiro extends javax.swing.JFrame {

    private int contadorJogadas = 0;
    private boolean ehJogador1 = true;
    private String[][] matriz = new String[3][3];

    /**
     * Creates new form Tabuleiro
     */
    public Tabuleiro() {
        initComponents();
        destacarJogador();
        TitledBorder border = (TitledBorder) pnlEmpates.getBorder();
        border.setTitleFont(border.getTitleFont().deriveFont(Font.PLAIN));
    }

    private void destacarJogador() {
        int fontJ1 = this.ehJogador1 ? Font.BOLD : Font.PLAIN;
        int fontJ2 = this.ehJogador1 ? Font.PLAIN : Font.BOLD;

        TitledBorder border1 = (TitledBorder) pnlJogador1.getBorder();
        border1.setTitleFont(border1.getTitleFont().deriveFont(fontJ1));
        TitledBorder border2 = (TitledBorder) pnlJogador2.getBorder();
        border2.setTitleFont(border2.getTitleFont().deriveFont(fontJ2));
        pnlJogador1.repaint();
        pnlJogador2.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        pnlJogador1 = new javax.swing.JPanel();
        lblPontosJ1 = new javax.swing.JLabel();
        pnlJogador2 = new javax.swing.JPanel();
        lblPontosJ2 = new javax.swing.JLabel();
        pnlEmpates = new javax.swing.JPanel();
        lblPontosE = new javax.swing.JLabel();
        btnCoor02 = new javax.swing.JToggleButton();
        btnCoor00 = new javax.swing.JToggleButton();
        btnCoor01 = new javax.swing.JToggleButton();
        btnCoor10 = new javax.swing.JToggleButton();
        btnCoor11 = new javax.swing.JToggleButton();
        btnCoor12 = new javax.swing.JToggleButton();
        btnCoor20 = new javax.swing.JToggleButton();
        btnCoor21 = new javax.swing.JToggleButton();
        btnCoor22 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Jogo da Velha");

        pnlJogador1.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogardor 1"));
        pnlJogador1.setPreferredSize(new java.awt.Dimension(120, 23));

        lblPontosJ1.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        lblPontosJ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPontosJ1.setText("0");

        javax.swing.GroupLayout pnlJogador1Layout = new javax.swing.GroupLayout(pnlJogador1);
        pnlJogador1.setLayout(pnlJogador1Layout);
        pnlJogador1Layout.setHorizontalGroup(
            pnlJogador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJogador1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPontosJ1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlJogador1Layout.setVerticalGroup(
            pnlJogador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJogador1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPontosJ1)
                .addContainerGap())
        );

        pnlJogador2.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogardor 2"));
        pnlJogador2.setPreferredSize(new java.awt.Dimension(120, 53));

        lblPontosJ2.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        lblPontosJ2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPontosJ2.setText("0");

        javax.swing.GroupLayout pnlJogador2Layout = new javax.swing.GroupLayout(pnlJogador2);
        pnlJogador2.setLayout(pnlJogador2Layout);
        pnlJogador2Layout.setHorizontalGroup(
            pnlJogador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJogador2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPontosJ2, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlJogador2Layout.setVerticalGroup(
            pnlJogador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJogador2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPontosJ2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEmpates.setBorder(javax.swing.BorderFactory.createTitledBorder("Empates"));
        pnlEmpates.setPreferredSize(new java.awt.Dimension(120, 53));

        lblPontosE.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        lblPontosE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPontosE.setText("0");

        javax.swing.GroupLayout pnlEmpatesLayout = new javax.swing.GroupLayout(pnlEmpates);
        pnlEmpates.setLayout(pnlEmpatesLayout);
        pnlEmpatesLayout.setHorizontalGroup(
            pnlEmpatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmpatesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPontosE, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlEmpatesLayout.setVerticalGroup(
            pnlEmpatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmpatesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPontosE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCoor02.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnCoor02.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCoor02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoor02ActionPerformed(evt);
            }
        });

        btnCoor00.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnCoor00.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCoor00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoor00ActionPerformed(evt);
            }
        });

        btnCoor01.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnCoor01.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCoor01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoor01ActionPerformed(evt);
            }
        });

        btnCoor10.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnCoor10.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCoor10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoor10ActionPerformed(evt);
            }
        });

        btnCoor11.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnCoor11.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCoor11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoor11ActionPerformed(evt);
            }
        });

        btnCoor12.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnCoor12.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCoor12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoor12ActionPerformed(evt);
            }
        });

        btnCoor20.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnCoor20.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCoor20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoor20ActionPerformed(evt);
            }
        });

        btnCoor21.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnCoor21.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCoor21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoor21ActionPerformed(evt);
            }
        });

        btnCoor22.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnCoor22.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCoor22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoor22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlEmpates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(pnlJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCoor20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCoor21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCoor22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCoor10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnCoor11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnCoor12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCoor00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnCoor01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnCoor02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlJogador2, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(pnlEmpates, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(pnlJogador1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCoor02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCoor00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCoor01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCoor12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCoor10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCoor11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCoor22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCoor20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCoor21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCoor00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoor00ActionPerformed
        this.executarJogada(btnCoor00, 0, 0);
    }//GEN-LAST:event_btnCoor00ActionPerformed

    private void btnCoor01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoor01ActionPerformed
        this.executarJogada(btnCoor01, 0, 1);
    }//GEN-LAST:event_btnCoor01ActionPerformed

    private void btnCoor02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoor02ActionPerformed
        this.executarJogada(btnCoor02, 0, 2);
    }//GEN-LAST:event_btnCoor02ActionPerformed

    private void btnCoor10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoor10ActionPerformed
        this.executarJogada(btnCoor10, 1, 0);
    }//GEN-LAST:event_btnCoor10ActionPerformed

    private void btnCoor11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoor11ActionPerformed
        this.executarJogada(btnCoor11, 1, 1);
    }//GEN-LAST:event_btnCoor11ActionPerformed

    private void btnCoor12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoor12ActionPerformed
        this.executarJogada(btnCoor12, 1, 2);
    }//GEN-LAST:event_btnCoor12ActionPerformed

    private void btnCoor20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoor20ActionPerformed
        this.executarJogada(btnCoor20, 2, 0);
    }//GEN-LAST:event_btnCoor20ActionPerformed

    private void btnCoor21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoor21ActionPerformed
        this.executarJogada(btnCoor21, 2, 1);
    }//GEN-LAST:event_btnCoor21ActionPerformed

    private void btnCoor22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoor22ActionPerformed
        this.executarJogada(btnCoor22, 2, 2);
    }//GEN-LAST:event_btnCoor22ActionPerformed

    private void executarJogada(JToggleButton botao, int i, int j) {
        contadorJogadas++;
        String marcador = ehJogador1 ? "X" : "O";
        botao.setText(marcador);
        botao.setEnabled(false);
        this.matriz[i][j] = marcador;
        if (contadorJogadas >= 5 && verificarVitoria()) {
            contabilizarVitoria();
            String jogador = ehJogador1 ? "Jogador 1" : "Jogador 2";
            JOptionPane.showMessageDialog(this,
                    jogador + " ganhou!", "Mensagem",
                    JOptionPane.INFORMATION_MESSAGE);
            reiniciar();
        } else if (contadorJogadas == 9) {
            Integer pontosE = Integer.valueOf(lblPontosE.getText()) + 1;
            lblPontosE.setText(pontosE.toString());
            JOptionPane.showMessageDialog(this,
                    "Deu velha!", "Mensagem",
                    JOptionPane.WARNING_MESSAGE);
        }
        ehJogador1 = !ehJogador1;
        destacarJogador();
    }

    private void reiniciar() {
        reiniciarBotoes(btnCoor00, btnCoor01, btnCoor02, btnCoor10, btnCoor11, btnCoor12, btnCoor20, btnCoor21, btnCoor22);
        contadorJogadas = 0;
        matriz = new String[3][3];
    }

    private void reiniciarBotoes(JToggleButton... buttons) {
        for (JToggleButton button : buttons) {
            button.setText("");
            button.setEnabled(true);
            button.setSelected(false);
        }
    }

    private void contabilizarVitoria() {
        if (ehJogador1) {
            Integer pontosJ1 = Integer.valueOf(lblPontosJ1.getText()) + 1;
            lblPontosJ1.setText(pontosJ1.toString());
        } else {
            Integer pontosJ2 = Integer.valueOf(lblPontosJ2.getText()) + 1;
            lblPontosJ2.setText(pontosJ2.toString());
        }
    }

    private boolean verificarVitoria() {
        return verificarVitoriaLinhas()
                || verificarVitoriaColunas()
                || verificarVitoriaDiagonais();
    }

    private boolean verificarVitoriaLinhas() {
        boolean retorno = false;
        for (int i = 0; i < 3; i++) {
            if (matriz[i][0] != null
                    && matriz[i][0].equals(matriz[i][1])
                    && matriz[i][0].equals(matriz[i][2])) {
                retorno = true;
                break;
            }
        }
        return retorno;
    }

    private boolean verificarVitoriaColunas() {
        boolean retorno = false;
        for (int j = 0; j < 3; j++) {
            if (matriz[0][j] != null
                    && matriz[0][j].equals(matriz[1][j])
                    && matriz[0][j].equals(matriz[2][j])) {
                retorno = true;
                break;
            }
        }
        return retorno;
    }

    private boolean verificarVitoriaDiagonais() {
        boolean retorno = false;
        if (matriz[0][0] != null
                && matriz[0][0].equals(matriz[1][1])
                && matriz[0][0].equals(matriz[2][2])) {
            retorno = true;
        } else if (matriz[2][0] != null
                && matriz[2][0].equals(matriz[1][1])
                && matriz[2][0].equals(matriz[0][2])) {
            retorno = true;
        }
        return retorno;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabuleiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCoor00;
    private javax.swing.JToggleButton btnCoor01;
    private javax.swing.JToggleButton btnCoor02;
    private javax.swing.JToggleButton btnCoor10;
    private javax.swing.JToggleButton btnCoor11;
    private javax.swing.JToggleButton btnCoor12;
    private javax.swing.JToggleButton btnCoor20;
    private javax.swing.JToggleButton btnCoor21;
    private javax.swing.JToggleButton btnCoor22;
    private javax.swing.JLabel lblPontosE;
    private javax.swing.JLabel lblPontosJ1;
    private javax.swing.JLabel lblPontosJ2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlEmpates;
    private javax.swing.JPanel pnlJogador1;
    private javax.swing.JPanel pnlJogador2;
    // End of variables declaration//GEN-END:variables

}
